DROP SEQUENCE G_SEQ;
DROP SEQUENCE C_SEQ;
DROP SEQUENCE P_SEQ;

DROP TABLE OWNER;
DROP TABLE GAMER;
DROP TABLE PLAYER;
DROP TABLE CLUB;

CREATE SEQUENCE G_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE C_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE P_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE CLUB (
    C_NO NUMBER DEFAULT C_SEQ.NEXTVAL CONSTRAINT C_PK PRIMARY KEY,
    C_NAME VARCHAR2(60) UNIQUE NOT NULL
);

CREATE TABLE GAMER (
    G_NO NUMBER DEFAULT G_SEQ.NEXTVAL CONSTRAINT G_PK PRIMARY KEY,
    C_NO NUMBER CONSTRAINT C_G_FK REFERENCES CLUB(C_NO) ON DELETE SET NULL,
    G_ID VARCHAR2(16) UNIQUE NOT NULL,
    G_PW VARCHAR2(16) NOT NULL,
    G_SESSIONID CHAR(32),
    G_ISADMIN NUMBER(1) DEFAULT 0 CHECK (G_ISADMIN IN (0, 1)) NOT NULL,
    G_BALANCE NUMBER(8) DEFAULT 100000 CHECK (G_BALANCE >= 0) NOT NULL,
    G_POINT NUMBER DEFAULT 0 CHECK (G_POINT >= 0) NOT NULL
);

CREATE TABLE PLAYER (
    P_NO NUMBER DEFAULT P_SEQ.NEXTVAL CONSTRAINT P_PK PRIMARY KEY,
    C_NO NUMBER CONSTRAINT C_P_FK REFERENCES CLUB(C_NO) ON DELETE SET NULL,
    P_NAME VARCHAR2(40) NOT NULL,
    P_UNIFORM_NO VARCHAR2(2) NOT NULL,
    P_POSITION VARCHAR2(2) NOT NULL,
    P_SHO NUMBER(2) CHECK (P_SHO > 0) NOT NULL,
    P_PAS NUMBER(2) CHECK (P_PAS > 0) NOT NULL,
    P_DEF NUMBER(2) CHECK (P_DEF > 0) NOT NULL,
    P_PRICE NUMBER(8) CHECK (P_PRICE > 0) NOT NULL
);

CREATE TABLE OWNER (
    G_NO NUMBER CONSTRAINT O_G_FK REFERENCES GAMER(G_NO) ON DELETE CASCADE,
    P_NO NUMBER CONSTRAINT O_P_FK REFERENCES PLAYER(P_NO) ON DELETE CASCADE
);

INSERT INTO CLUB (C_NAME) VALUES ('Tottenham Spurs');
INSERT INTO CLUB (C_NAME) VALUES ('Manchester City');
INSERT INTO CLUB (C_NAME) VALUES ('Barcelona');
INSERT INTO CLUB (C_NAME) VALUES ('KH 352 FC');

INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Heung Min Son', 7,'fw', 82, 60, 40, 98000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Richarlison', 9,'fw', 81, 60, 40, 46000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Brennan Johnson', 22,'fw', 78, 60, 40, 36000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'James Maddison', 10,'mf', 60, 70, 50, 88000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Rodrigo Bentancur', 30,'mf', 60, 70, 50, 39000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Pierre-Emile Højbjerg', 5,'mf', 60, 70, 50, 52000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Pedro Porro', 23,'df', 40, 80, 80, 44000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Cristian Romero', 17,'df', 40, 80, 80, 85000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Micky van de Ven', 37,'df', 40, 80, 80, 26000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Destiny Udogie', 4,'df', 40, 80, 80, 39000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (1, 'Guglielmo Vicario', 13, 'gk', 20, 90, 80, 39000);

INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Erling Haaland', 9, 'fw', 82, 60, 40,  195000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Phil Foden', 47, 'fw', 83, 60, 40,  117000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Jack Grealishn', 10, 'fw', 75, 60, 40,  156000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Kevin De Bruyne', 17, 'mf', 80, 60, 40,  208000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Rodri', 16, 'mf', 81, 70, 50,  114000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Bernardo Silva', 20, 'mf', 79, 70, 50,  156000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Kyle Walker', 2, 'df', 40, 80, 80,  91000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Nathan Aké', 6, 'df', 40, 80, 80,  83000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Joško Gvardiol', 24, 'df', 40, 80, 80,  104000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Sergio Gómez', 21, 'df', 40, 80, 80,  39000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (2, 'Stefan Ortega', 18, 'gk', 20, 90, 80,  28000);

INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Lewandowski', 9, 'fw', 86, 60, 40,  120000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Lamin Yamal', 27, 'fw', 83, 60, 40,  125000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Joao Felix', 14, 'fw', 79, 60, 40,  50000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Frenkie De Jong', 21, 'mf', 60, 70, 50,  130000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Ilkay Gundogan', 22, 'mf', 60, 70, 50,  85000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Pedri', 8, 'mf', 60, 70, 50,  130000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Balde', 3, 'df', 40,  80, 80,  115000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Jules Kounde', 23, 'df', 40, 80, 80,  95000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Ronald Araujo', 4, 'df', 40, 80, 80,  115000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Joao Cancelo', 2, 'df', 40, 80, 80,  80000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (3, 'Marc-Andre Ter Stergen', 1, 'gk', 20, 90, 80,  115000);

INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Kim Dong Jin', 7, 'fw', 99, 99, 99,  999999);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Jung Woo Kyeong', 9, 'fw', 79, 60, 40,  125000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Yoon Jun Ho', 10, 'fw', 81, 60, 40,  500000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Kim Geonu', 12, 'mf', 99, 99, 99,  130000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Lee Suk Jin', 8, 'mf', 60, 70, 50,  85000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'An Ji Hoon', 16, 'mf', 60, 70, 50,  115000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Choi Sung Lak', 6, 'df', 40, 80, 80,  130000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Shin Joong Woo', 23, 'df', 40, 80, 80,  95000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Kang Ji Hoon', 2, 'df', 40, 80, 80,  80000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Cha Jae Kyeong', 1, 'df', 40, 80, 80,  115000);
INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) VALUES (4, 'Kwak Ki Myeong', 99, 'gk', 20, 90, 80,  120000);

COMMIT;

CREATE OR REPLACE PROCEDURE INSERTCLUB (V_C_NAME IN VARCHAR2)
IS
BEGIN
    INSERT INTO CLUB (C_NAME) VALUES (V_C_NAME);
END;
/

CREATE OR REPLACE PROCEDURE DELETECLUB (V_C_NO IN NUMBER)
IS
BEGIN
    DELETE FROM CLUB WHERE C_NO = V_C_NO;
END;
/

CREATE OR REPLACE PROCEDURE UPDATECLUB (V_C_NAME IN VARCHAR2, V_C_NO IN NUMBER)
IS
BEGIN
    UPDATE CLUB SET C_NAME = V_C_NAME WHERE C_NO = V_C_NO;
END;
/

CREATE OR REPLACE PROCEDURE INSERTPLAYER (
    V_C_NO IN NUMBER, 
    V_P_NAME IN VARCHAR2, 
    V_P_UNIFORM_NO IN NUMBER, 
    V_P_POSITION IN VARCHAR2, 
    V_P_SHO IN NUMBER, 
    V_P_PAS IN NUMBER, 
    V_P_DEF IN NUMBER, 
    V_P_PRICE IN NUMBER
    )
IS
BEGIN
    INSERT INTO PLAYER (C_NO, P_NAME, P_UNIFORM_NO, P_POSITION, P_SHO, P_PAS, P_DEF, P_PRICE) 
    VALUES (V_C_NO, V_P_NAME, V_P_UNIFORM_NO, V_P_POSITION, V_P_SHO, V_P_PAS, V_P_DEF, V_P_PRICE);
END;
/

CREATE OR REPLACE PROCEDURE DELETEPLAYER (V_P_NO IN NUMBER)
IS
BEGIN
    DELETE FROM PLAYER WHERE P_NO = V_P_NO;
END;
/

CREATE OR REPLACE PROCEDURE UPDATEPLAYER (
    V_C_NO IN NUMBER, 
    V_P_NAME IN VARCHAR2, 
    V_P_UNIFORM_NO IN NUMBER, 
    V_P_POSITION IN VARCHAR2, 
    V_P_SHO IN NUMBER, 
    V_P_PAS IN NUMBER, 
    V_P_DEF IN NUMBER, 
    V_P_PRICE IN NUMBER,
    V_P_NO IN NUMBER
    )
IS
BEGIN
    UPDATE PLAYER SET C_NO = V_C_NO, P_NAME = V_P_NAME, P_UNIFORM_NO = V_P_UNIFORM_NO, P_POSITION = V_P_POSITION, 
    P_SHO = V_P_SHO, P_PAS = V_P_PAS, P_DEF = V_P_DEF, P_PRICE = V_P_PRICE WHERE P_NO = V_P_NO;
END;
/

CREATE OR REPLACE PROCEDURE REGISTER(
    V_C_NO IN NUMBER,
    V_G_ID IN VARCHAR2,
    V_G_PW IN VARCHAR2
)
IS
BEGIN
    INSERT INTO GAMER(C_NO, G_ID, G_PW) VALUES(V_C_NO, V_G_ID, V_G_PW);
END;
/

CREATE OR REPLACE TRIGGER AFTER_REGISTER
AFTER INSERT ON GAMER
FOR EACH ROW
BEGIN
    INSERT INTO OWNER(G_NO, P_NO)
    SELECT :NEW.G_NO, P_NO FROM PLAYER WHERE C_NO = :NEW.C_NO;
END;
/

CREATE OR REPLACE PROCEDURE LOGIN(
    V_G_ID IN VARCHAR2,
    V_G_PW IN VARCHAR2,
    V_G_SESSIONID OUT VARCHAR2,
    V_G_ISADMIN OUT NUMBER
)
IS
    V_G_NO NUMBER;
BEGIN
    UPDATE GAMER 
    SET G_SESSIONID = SYS_GUID() 
    WHERE G_ID = V_G_ID 
    AND G_PW = V_G_PW
    RETURNING G_NO, G_SESSIONID, G_ISADMIN INTO V_G_NO, V_G_SESSIONID, V_G_ISADMIN;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_G_SESSIONID := NULL;
            V_G_ISADMIN := 0;
        WHEN OTHERS THEN
            V_G_SESSIONID := NULL;
            V_G_ISADMIN := 0;
END;
/

CREATE OR REPLACE PROCEDURE LOGOUT(
    V_G_SESSIONID IN VARCHAR2
)
IS
BEGIN
    UPDATE GAMER SET G_SESSIONID = NULL WHERE G_SESSIONID = V_G_SESSIONID;
END;
/

CREATE OR REPLACE PROCEDURE SELLPLAYER(
    V_G_SESSIONID IN VARCHAR2,
    V_P_NO IN NUMBER,
    V_RESULT OUT NUMBER
)
IS
    V_G_NO NUMBER;
    V_P_PRICE NUMBER;
BEGIN
    SELECT G_NO INTO V_G_NO FROM GAMER WHERE G_SESSIONID = V_G_SESSIONID;
    SELECT P_PRICE INTO V_P_PRICE FROM PLAYER WHERE P_NO = V_P_NO;
    DELETE FROM OWNER WHERE G_NO = V_G_NO AND P_NO = V_P_NO;
    IF SQL%ROWCOUNT > 0 THEN
        UPDATE GAMER SET G_BALANCE = G_BALANCE + V_P_PRICE WHERE G_NO = V_G_NO;
        V_RESULT := 1;
    ELSE
        V_RESULT := 0;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE BUYPLAYER(
    V_G_SESSIONID IN VARCHAR2,
    V_P_NO IN NUMBER,
     V_RESULT OUT NUMBER
)
IS
    V_G_NO NUMBER;
    V_P_PRICE NUMBER;
    V_G_BALANCE NUMBER;
BEGIN
    SELECT G_NO, G_BALANCE INTO V_G_NO, V_G_BALANCE FROM GAMER WHERE G_SESSIONID = V_G_SESSIONID;
    SELECT P_PRICE INTO V_P_PRICE FROM PLAYER WHERE P_NO = V_P_NO;
    IF V_P_PRICE < V_G_BALANCE THEN
        UPDATE GAMER SET G_BALANCE = G_BALANCE - V_P_PRICE;
        INSERT INTO OWNER VALUES(V_G_NO, V_P_NO);
        V_RESULT := 1;
    ELSE
        V_RESULT := 0;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE POINTUP(V_G_SESSIONID IN VARCHAR2)
IS
BEGIN
    UPDATE GAMER SET G_POINT = G_POINT + 1 WHERE G_SESSIONID = V_G_SESSIONID;
END;
/

SELECT * FROM OWNER;
SELECT * FROM PLAYER;
SELECT * FROM CLUB;
SELECT * FROM GAMER;

UPDATE GAMER SET G_ISADMIN = 1 WHERE G_NO = 1;